replicaCount: 2

image:
  repository: ghcr.io/yassineboubkeur/product-service
  tag: 84d444b
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 5000

env:
  PORT: "5000"
  NODE_ENV: "production"
  DB_HOST: "pg"
  DB_PORT: "5432"
  DB_NAME: "productdb"

secrets:
  name: product-service-secret

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 30
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10