replicaCount: 2

image:
  repository: ghcr.io/yassineboubkeur/api-gateway
  tag: a3afde4
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 3000

env:
  PORT: "3000"
  NODE_ENV: "production"
  USER_SERVICE_URL: "http://user-service:4000"
  PRODUCT_SERVICE_URL: "http://product-service:5000"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  host: microservices.local

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 30
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10