replicaCount: 1

image:
  tag: latest

env:
  NODE_ENV: "development"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

ingress:
  host: microservices.local