name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  REGISTRY: ghcr.io
  USERNAME: yassineboubkeur

jobs:
  build-api-gateway:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./services/api-gateway
          push: true
          tags: |
            ghcr.io/${{ env.USERNAME }}/api-gateway:latest
            ghcr.io/${{ env.USERNAME }}/api-gateway:${{ github.sha }}

  build-user-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push User Service
        uses: docker/build-push-action@v5
        with:
          context: ./services/user-service
          push: true
          tags: |
            ghcr.io/${{ env.USERNAME }}/user-service:latest
            ghcr.io/${{ env.USERNAME }}/user-service:${{ github.sha }}

  build-product-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Product Service
        uses: docker/build-push-action@v5
        with:
          context: ./services/product-service
          push: true
          tags: |
            ghcr.io/${{ env.USERNAME }}/product-service:latest
            ghcr.io/${{ env.USERNAME }}/product-service:${{ github.sha }}