replicaCount: 1

image:
  tag: latest

env:
  NODE_ENV: "development"
  DB_HOST: "pg"
  DB_NAME: "userdb"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"